### ISSUE TITLE
index.html - Syntax error

### ISSUE THREAD

**Issue by larsyngvelundin** [felle64/BEB-Grupp3#12]
Där är ju en massa syntax fel i Index.html
Vem tusan godkände dessa merges????

33 - `<body`
34 - `    <h1>Min ändring är viktigast</h1>`
35 - `    <h1>Min ändring är viktigast</h1>`
36 - `    <h1>Min ändring är viktigast</h1>`
37 - `main`
38 - 
39 - `</body>`

**Comment by felle64** [comment]
felle64 approved these changes 28 minutes ago
